### ISSUE TITLE
Publisher table is not updated in DB when publishing activity

### ISSUE THREAD

**Issue by zijian-hu** [DIAYN/USC_CampuSee_Backend#1]
**Issue**: When publishing activities, the `publisherID` filed in the request is only updated in the **activity table** but not in **publisher table**

**Potential fix**: update

https://github.com/DIAYN/USC_CampuSee_Backend/blob/364e761d147fa6df22f699537662385add8b47fd/src/database/MongoDB.java#L378-L379

so that when publishing new activities, the corresponding publisher will also be updated

**Comment by zijian-hu** [comment]
`Activity addActivity(Activity activity)` should be updated so that when publishing new activities, the corresponding publisher will also be updated

**Comment by zijian-hu** [comment]
resolved in
https://github.com/DIAYN/USC_CampuSee_Backend/blob/cdbf1557e8b2924b932f1ac71237e576bc6b35e8/src/database/MongoDB.java#L641-L663

**Comment by yuyangh** [comment]
solved
