### ISSUE TITLE
Upload activity image does not update activity table in DB

### ISSUE THREAD

**Issue by zijian-hu** [DIAYN/USC_CampuSee_Backend#4]
**Issue**: When uploading activity images, the `imageIds` column of **activity table** is not updated

**Comment by yuyangh** [comment]
fixed

**Comment by zijian-hu** [comment]
Fixed with the following update

https://github.com/DIAYN/USC_CampuSee_Backend/blob/391c34a8c1439d5b3ed28b40f023c204d74c2bbb/src/database/MongoDB.java#L696-L706

https://github.com/DIAYN/USC_CampuSee_Backend/blob/391c34a8c1439d5b3ed28b40f023c204d74c2bbb/src/service/FileService.java#L150-L162
