### ISSUE TITLE
Upload activity image in DB does not handle duplications

### ISSUE THREAD

**Issue by zijian-hu** [DIAYN/USC_CampuSee_Backend#6]
**Issue**: when uploading activity image, the request must include `activityID` and `imageID` where `imageID` is appended to `imageIds` column of **activity table** in DB. However, when a subsequent request with the same `activityID` and `imageID` is sent. Duplicated imageID will be appened to `imageIds` column in DB

**Comment by yuyangh** [comment]
fix addActivityImageId with duplicate check. Also test in junit

**Comment by zijian-hu** [comment]
fixed with the following changes
https://github.com/DIAYN/USC_CampuSee_Backend/blob/99181d4497903fc2098660614705f9d0792f1b08/src/service/FileService.java#L147

https://github.com/DIAYN/USC_CampuSee_Backend/blob/99181d4497903fc2098660614705f9d0792f1b08/src/service/FileService.java#L158-L175

https://github.com/DIAYN/USC_CampuSee_Backend/blob/99181d4497903fc2098660614705f9d0792f1b08/src/database/MongoDB.java#L707-L717
